---

- stat:
    path: /etc/xinetd.d/chargen
  register: chargen_file
  failed_when: False
  ignore_errors: True
  changed_when: False
  tags:
    - section2
    - section2.1
    - section2.1.1

- name: 2.1.1 Ensure chargen services are not enabled (Scored)
  lineinfile:
    dest: /etc/xinetd.d/chargen
    regexp: '^disable                = yes'
    line: 'disable           = yes'
  when: chargen_file.stat.exists
  tags:
    - section2
    - section2.1
    - section2.1.1

- stat:
    path: /etc/xinetd.d/daytime
  register: daytime_file
  failed_when: False
  ignore_errors: True
  changed_when: False
  tags:
    - section2
    - section2.1
    - section2.1.2

- name: 2.1.2 Ensure daytime services are not enabled (Scored)
  lineinfile:
    dest: /etc/xinetd.d/daytime
    regexp: '^disable                = yes'
    line: 'disable           = yes'
  when: daytime_file.stat.exists
  tags:
    - section2
    - section2.1
    - section2.1.2

- stat:
    path: /etc/xinetd.d/discard
  register: discard_file
  failed_when: False
  ignore_errors: True
  changed_when: False
  tags:
    - section2
    - section2.1
    - section2.1.3

- name: 2.1.3 Ensure discard services are not enabled (Scored)
  lineinfile:
    dest: /etc/xinetd.d/discard
    regexp: '^disable                = yes'
    line: 'disable           = yes'
  when: discard_file.stat.exists
  tags:
    - section2
    - section2.1
    - section2.1.3

- stat:
    path: /etc/xinetd.d/echo
  register: echo_file
  failed_when: False
  ignore_errors: True
  changed_when: False
  tags:
    - section2
    - section2.1
    - section2.1.4

- name: 2.1.4 Ensure echo services are not enabled (Scored)
  lineinfile:
    dest: /etc/xinetd.d/echo
    regexp: '^disable                = yes'
    line: 'disable           = yes'
  when: echo_file.stat.exists
  tags:
    - section2
    - section2.1
    - section2.1.4

- stat:
    path: /etc/xinetd.d/time
  register: time_file
  failed_when: False
  ignore_errors: True
  changed_when: False
  tags:
    - section2
    - section2.1
    - section2.1.5

- name: 2.1.5 Ensure time services are not enabled (Scored)
  lineinfile:
    dest: /etc/xinetd.d/time
    regexp: '^disable                = yes'
    line: 'disable           = yes'
  when: time_file.stat.exists
  tags:
    - section2
    - section2.1
    - section2.1.5

- stat:
    path: /etc/xinetd.d/rsh
  register: rsh_file
  failed_when: False
  ignore_errors: True
  changed_when: False
  tags:
    - section2
    - section2.1
    - section2.1.6

- name: 2.1.6 Ensure rsh server is not enabled (Scored)
  lineinfile:
    dest: /etc/xinetd.d/rsh
    regexp: '^disable                = yes'
    line: 'disable           = yes'
  when: rsh_file.stat.exists
  tags:
    - section2
    - section2.1
    - section2.1.6

- stat:
    path: /etc/xinetd.d/talk
  register: talk_file
  failed_when: False
  ignore_errors: True
  changed_when: False
  tags:
    - section2
    - section2.1
    - section2.1.7

- name: 2.1.7 Ensure talk server is not enabled (Scored)
  lineinfile:
    dest: /etc/xinetd.d/talk
    regexp: '^disable                = yes'
    line: 'disable           = yes'
  when: talk_file.stat.exists
  tags:
    - section2
    - section2.1
    - section2.1.7

- stat:
    path: /etc/xinetd.d/telnet
  register: telnet_file
  failed_when: False
  ignore_errors: True
  changed_when: False
  tags:
    - section2
    - section2.1
    - section2.1.8

- name: 2.1.8 Ensure telnet server is not enabled (Scored)
  lineinfile:
    dest: /etc/xinetd.d/telnet
    regexp: '^disable                = yes'
    line: 'disable           = yes'
  when: telnet_file.stat.exists
  tags:
    - section2
    - section2.1
    - section2.1.8

- stat:
    path: /etc/xinetd.d/tftp
  register: tftp_file
  failed_when: False
  ignore_errors: True
  changed_when: False
  tags:
    - section2
    - section2.1
    - section2.1.9

- name: 2.1.9 Ensure tftp server is not enabled (Scored)
  lineinfile:
    dest: /etc/xinetd.d/tftp
    regexp: '^disable                = yes'
    line: 'disable           = yes'
  when: tftp_file.stat.exists
  tags:
    - section2
    - section2.1
    - section2.1.9

- command: dpkg -l xinetd
  register: xinetd_installed
  failed_when: False
  ignore_errors: True
  changed_when: False
  tags:
    - section2
    - section2.1
    - section2.1.10

- name: 2.1.10 Ensure xinetd is not enabled (Scored)
  systemd:
    name: xinetd
    state: stopped
  when: xinetd_installed.rc == 0
  tags:
    - section2
    - section2.1
    - section2.1.10
