---

- name: 1.7.1.1 Ensure message of the day is configured properly (Scored)
  template:
    src: motd.j2
    dest: /etc/motd
    owner: root
    group: root
    mode: 0644
  tags:
    - section1
    - section1.7
    - section1.7.1.1
    - section1.7.1.4

- name: 1.7.1.2 Ensure local login warning banner is configured properly (Not Scored)
  copy:
    src: issue
    dest: /etc/issue
    owner: root
    group: root
    mode: 0644
  tags:
    - section1
    - section1.7
    - section1.7.1.2
    - section1.7.1.5

- name: 1.7.1.3 Ensure remote login warning banner is configured properly (Not Scored)
  copy:
    src: issue
    dest: /etc/issue.net
    owner: root
    group: root
    mode: 0644
  tags:
    - section1
    - section1.7
    - section1.7.1.3
    - section1.7.1.7
