---

- name: 1.3.1 Ensure AIDE is installed (Scored)
  apt:
    name: aide
    state: present
  tags:
    - section1
    - section1.3
    - section1.3.1

- name: Delete /etc/cron.daily/aide because we have a custom script
  file:
    path: /etc/cron.daily/aide
    state: absent
  tags:
    - section1
    - section1.3

- name: Drop in aide.conf with customizations for Docker/kubernetes
  template:
    src: aide.conf.j2
    dest: /etc/aide/aide.conf

 # We might use this later so we kept it in
- name: Check if aide.db exists
  stat:
    path: /var/lib/aide/aide.db
  register: aide_db_exists
  tags:
    - section1.3
    - aideinit

- name: Initialize aide
  when: aide_db_exists.stat.exists == False
  command: aideinit
  register: aide_new_init
  tags:
    - section1.3
    - aideinit
  notify:
    - copy_aide_db

- name: Get checksum of aide.conf to see if we need to copy the autogend conf
  stat:
    path: /etc/aide/aide.conf
    get_md5: yes
  register: aide_conf_md5sum
  tags:
    - section1.3

- name: Copy config
  command: cp /var/lib/aide/aide.conf.autogenerated /etc/aide/aide.conf
  when: aide_conf_md5sum.stat.md5 == 'e87472b306db896f1bc7d990ebd81af7'
  tags:
    - section1.3

- name: Copy aide_check script to /usr/bin
  copy:
    src: aide_check.sh
    dest: /usr/bin/aide_check
    mode: 0775
    owner: root
    group: root
  tags:
    - section1.3

- name: 1.3.2 Ensure filesystem integrity is regularly checked (Scored)
  cron:
    name: "Check files integrity"
    minute: 0
    hour: 5
    job: "/usr/bin/aide_check"
    state: absent
  tags:
    - section1
    - section1.3
    - section1.3.2
