---

- apt:
    name: auditd
    state: present
  when: enable_auditd == True
  tags:
    - section4
    - section4.1
    - section4.1.1.1

- name: Auditd should own its log file
  ignore_errors: true
  file:
    path: "{{ item }}"
    mode: 0640
  with_items:
    - '/var/log/audit'
    - '/var/log/audit/audit.log'

- name: Drop in auditd.conf
  template:
    src: auditd.conf.j2
    dest: /etc/audit/auditd.conf
    owner: root
    group: root
  notify:
    - restart auditd
  tags:
    - section4
    - section4.1
    - section4.1.1.1
    - section4.1.1.2
    - section4.1.1.3

- name: 4.1.2 Ensure auditd service is enabled (Scored)
  service:
    name: auditd
    enabled: yes
  when: enable_auditd == True
  tags:
    - section4
    - section4.1
    - section4.1.2

- name: 4.1.3 Ensure auditing for processes that start prior to auditd is enabled (Scored)
  lineinfile:
    dest: /etc/default/grub
    line: 'GRUB_CMDLINE_LINUX="audit=1"'
  tags:
    - section4
    - section4.1
    - section4.1.3

- name: 4.1.4 - 4.1.18 Drop in audit.rules template
  template:
    src: audit.rules.j2
    dest: /etc/audit/audit.rules
    owner: root
    group: root
    mode: 0640
  notify:
    - restart auditd
  when: enable_auditd == True

- name: Make sure auditd is started
  systemd:
    name: auditd
    state: started
    enabled: yes
