---

- name: 5.3.1 Ensure password creation requirements are configured (Scored)
  apt:
    name: libpam-pwquality
    state: present
  tags:
    - section5
    - section5.3
    - section5.3.1

- name: 5.3.1 Ensure password creation requirements are configured (Scored)
  lineinfile:
    name: /etc/security/pwquality.conf
    regexp: '^{{item.name}}'
    line: '{{item.name}}={{item.value}}'
  with_items:
    - {name: 'minlen', value: '14'}
    - {name: 'dcredit', value: '-1'}
    - {name: 'ucredit', value: '-1'}
    - {name: 'ocredit', value: '-1'}
    - {name: 'lcredit', value: '-1'}
  tags:
    - section5
    - section5.3
    - section5.3.1

- name: 5.3.1 Ensure password creation requirements are configured (Scored)
  lineinfile:
    name: /etc/pam.d/common-password
    regexp: 'pam_pwquality.so'
    line: 'password        requisite                       pam_pwquality.so try_first_pass retry=3'
  tags:
    - section5
    - section5.3
    - section5.3.1

- name: 5.3.2 Ensure lockout for failed password attempts is configured (Not Scored)
  lineinfile:
    name: /etc/pam.d/common-auth
    regexp: 'pam_tally2'
    line: 'auth required pam_tally2.so onerr=fail audit silent deny=5 unlock_time=900'
  tags:
    - section5
    - section5.3
    - section5.3.2

- name: 5.3.3 Ensure password reuse is limited (Scored)
  lineinfile:
    name: /etc/pam.d/common-password
    regexp: '^password\s+sufficient\s+pam_unix.so'
    line: 'password sufficient pam_unix.so remember=5'
  tags:
    - section5
    - section5.3
    - section5.3.3

- name: 5.3.4 Ensure password hashing algorithm is SHA-512 (Scored)
  lineinfile:
    name: /etc/pam.d/common-password
    regexp: '^password\s+\S+\s+pam_unix.so'
    line: 'password sufficient pam_unix.so sha512'
  tags:
    - section5
    - section5.3
    - section5.3.4
